version: '3.5'

services:

  api:
    build: ./api
    container_name: test-api
    depends_on:
      - db
    restart: always
    networks:
      - overlay
    ports:
      - 5000:5000

  db:
    image: postgres:11-alpine
    container_name: test-db
    restart: always
    environment:
      - GUNICORN_WORKER_TYPE=sync  # gevent, eventlet, ...
    networks:
      - overlay
    expose:
      - 5432


networks:
  overlay:


